# Generated by Django 5.0 on 2023-12-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_description_expense_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='correo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='direccion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
