# Generated by Django 5.0 on 2023-12-13 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_correo_expense_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comercial',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
