# Generated by Django 5.0 on 2023-12-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_comercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comercial',
            field=models.TextField(default='Nombre Comercial'),
        ),
    ]
