# Generated by Django 5.0 on 2023-12-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='comercial',
        ),
    ]
