# Generated by Django 5.0 on 2023-12-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_remove_expense_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comercial',
            field=models.TextField(default='Nombre Comercial'),
            preserve_default=False,
        ),
    ]
