# Generated by Django 5.0 on 2023-12-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='nuevo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
