# Generated by Django 5.0 on 2023-12-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_nuevo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='nuevo',
        ),
    ]
