# Generated by Django 5.0 on 2023-12-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_remove_expense_nuevo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fecha',
            field=models.DateField(),
        ),
    ]
