# Generated by Django 5.0 on 2023-12-13 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expense_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
