# Generated by Django 5.0 on 2023-12-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_provincia_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AddField(
            model_name='expense',
            name='provincia',
            field=models.CharField(default='provincia'),
            preserve_default=False,
        ),
    ]
