# Generated by Django 5.0 on 2023-12-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expense_cedula_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cedula_ruc',
            field=models.TextField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='nombre',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='nombre_comercial',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='razon_social',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='representantelegal',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
