# Generated by Django 5.0 on 2024-01-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_lineas'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='latitud_comercial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='latitud_domicilio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='longitud_comercial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='longitud_domicilio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
