# Generated by Django 5.0.1 on 2024-01-16 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_clase_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mes',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
